import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import AuthProvider from "./components/AuthProvider";
import StoreProvider from "@/store/storeProvider";
import SwiperComponent from "./components/Swiper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <AuthProvider>
          <body>
            <Nav />

            {children}
          </body>
        </AuthProvider>
      </html>
    </StoreProvider>
  );
}
